# -*- coding: utf-8 -*-
import scrapy
# 导入item
from pythondemo.items import PythondemoItem


class Beauty07Spider(scrapy.Spider):
    name = 'beauty07'
    allowed_domains = ['mm.enterdesk.com']
    start_urls = [
        'https://mm.enterdesk.com/1.html',
        'https://mm.enterdesk.com/2.html',
        'https://mm.enterdesk.com/3.html',
        'https://mm.enterdesk.com/4.html',
        'https://mm.enterdesk.com/5.html',
        'https://mm.enterdesk.com/6.html',
        'https://mm.enterdesk.com/7.html',
        'https://mm.enterdesk.com/8.html',
        'https://mm.enterdesk.com/9.html',
        'https://mm.enterdesk.com/10.html',
        'https://mm.enterdesk.com/11.html',
        'https://mm.enterdesk.com/12.html',
        'https://mm.enterdesk.com/13.html',
        'https://mm.enterdesk.com/14.html',
        'https://mm.enterdesk.com/15.html',
        'https://mm.enterdesk.com/16.html',
        'https://mm.enterdesk.com/17.html',
        'https://mm.enterdesk.com/18.html',
        'https://mm.enterdesk.com/19.html',

        'https://mm.enterdesk.com/20.html',
        'https://mm.enterdesk.com/21.html',
        'https://mm.enterdesk.com/22.html',
        'https://mm.enterdesk.com/23.html',
        'https://mm.enterdesk.com/24.html',
        'https://mm.enterdesk.com/25.html',
        'https://mm.enterdesk.com/26.html',
        'https://mm.enterdesk.com/27.html',
        'https://mm.enterdesk.com/28.html',
        'https://mm.enterdesk.com/29.html',

        'https://mm.enterdesk.com/30.html',
        'https://mm.enterdesk.com/31.html',
        'https://mm.enterdesk.com/32.html',
        'https://mm.enterdesk.com/33.html',
        'https://mm.enterdesk.com/34.html',
        'https://mm.enterdesk.com/35.html',
        'https://mm.enterdesk.com/36.html',
        'https://mm.enterdesk.com/37.html',
        'https://mm.enterdesk.com/38.html',
        'https://mm.enterdesk.com/39.html',

        'https://mm.enterdesk.com/40.html',
        'https://mm.enterdesk.com/41.html',
        'https://mm.enterdesk.com/42.html',
        'https://mm.enterdesk.com/43.html',
        'https://mm.enterdesk.com/44.html',
        'https://mm.enterdesk.com/45.html',
        'https://mm.enterdesk.com/46.html',
        'https://mm.enterdesk.com/47.html',
        'https://mm.enterdesk.com/48.html',
        'https://mm.enterdesk.com/49.html',

        'https://mm.enterdesk.com/50.html',
        'https://mm.enterdesk.com/51.html',
        'https://mm.enterdesk.com/52.html',
        'https://mm.enterdesk.com/53.html',
        'https://mm.enterdesk.com/54.html',
        'https://mm.enterdesk.com/55.html',
        'https://mm.enterdesk.com/56.html',
        'https://mm.enterdesk.com/57.html',
        'https://mm.enterdesk.com/58.html',
        'https://mm.enterdesk.com/59.html',

        'https://mm.enterdesk.com/60.html',
        'https://mm.enterdesk.com/61.html',
        'https://mm.enterdesk.com/62.html',
        'https://mm.enterdesk.com/63.html',
        'https://mm.enterdesk.com/64.html',
        'https://mm.enterdesk.com/65.html',
        'https://mm.enterdesk.com/66.html',
        'https://mm.enterdesk.com/67.html',
        'https://mm.enterdesk.com/68.html',
        'https://mm.enterdesk.com/69.html',

        'https://mm.enterdesk.com/70.html',
        'https://mm.enterdesk.com/71.html',
        'https://mm.enterdesk.com/72.html',
        'https://mm.enterdesk.com/73.html',
        'https://mm.enterdesk.com/74.html',
        'https://mm.enterdesk.com/75.html',
        'https://mm.enterdesk.com/76.html',
        'https://mm.enterdesk.com/77.html',
        'https://mm.enterdesk.com/78.html',
        'https://mm.enterdesk.com/79.html',

        'https://mm.enterdesk.com/80.html',
        'https://mm.enterdesk.com/81.html',
        'https://mm.enterdesk.com/82.html',
        'https://mm.enterdesk.com/83.html',
        'https://mm.enterdesk.com/84.html',
        'https://mm.enterdesk.com/85.html',
        'https://mm.enterdesk.com/86.html',
        'https://mm.enterdesk.com/87.html',
        'https://mm.enterdesk.com/88.html',
        'https://mm.enterdesk.com/89.html',

        'https://mm.enterdesk.com/90.html',
        'https://mm.enterdesk.com/91.html',
        'https://mm.enterdesk.com/92.html',
        'https://mm.enterdesk.com/93.html',
        'https://mm.enterdesk.com/94.html',
        'https://mm.enterdesk.com/95.html',
        'https://mm.enterdesk.com/96.html',
        'https://mm.enterdesk.com/97.html',
        'https://mm.enterdesk.com/98.html',
        'https://mm.enterdesk.com/99.html',

        'https://mm.enterdesk.com/101.html',
        'https://mm.enterdesk.com/102.html',
        'https://mm.enterdesk.com/103.html',
        'https://mm.enterdesk.com/104.html',
        'https://mm.enterdesk.com/105.html',
        'https://mm.enterdesk.com/106.html',
        'https://mm.enterdesk.com/107.html',
        'https://mm.enterdesk.com/108.html',
        'https://mm.enterdesk.com/109.html',
        'https://mm.enterdesk.com/110.html',
        'https://mm.enterdesk.com/111.html',
        'https://mm.enterdesk.com/112.html',
        'https://mm.enterdesk.com/113.html',
        'https://mm.enterdesk.com/114.html',
        'https://mm.enterdesk.com/115.html',
        'https://mm.enterdesk.com/116.html',
        'https://mm.enterdesk.com/117.html',
        'https://mm.enterdesk.com/118.html',
        'https://mm.enterdesk.com/119.html',
        'https://mm.enterdesk.com/120.html',
        'https://mm.enterdesk.com/121.html',
        'https://mm.enterdesk.com/122.html',
        'https://mm.enterdesk.com/123.html',
        'https://mm.enterdesk.com/124.html',
        'https://mm.enterdesk.com/125.html',
        'https://mm.enterdesk.com/126.html',
        'https://mm.enterdesk.com/127.html',
        'https://mm.enterdesk.com/128.html',
        'https://mm.enterdesk.com/129.html',
        'https://mm.enterdesk.com/130.html',
        'https://mm.enterdesk.com/131.html',
        'https://mm.enterdesk.com/132.html',
        'https://mm.enterdesk.com/133.html',
        'https://mm.enterdesk.com/134.html',
        'https://mm.enterdesk.com/135.html',
        'https://mm.enterdesk.com/136.html',
        'https://mm.enterdesk.com/137.html',
        'https://mm.enterdesk.com/138.html',
        'https://mm.enterdesk.com/139.html',
        'https://mm.enterdesk.com/140.html',
        'https://mm.enterdesk.com/141.html',
        'https://mm.enterdesk.com/142.html',
        'https://mm.enterdesk.com/143.html',
        'https://mm.enterdesk.com/144.html',
        'https://mm.enterdesk.com/145.html',
        'https://mm.enterdesk.com/146.html',
        'https://mm.enterdesk.com/147.html',
        'https://mm.enterdesk.com/148.html',
        'https://mm.enterdesk.com/149.html',

        'https://mm.enterdesk.com/150.html',
        'https://mm.enterdesk.com/151.html',
        'https://mm.enterdesk.com/152.html',
        'https://mm.enterdesk.com/153.html',
        'https://mm.enterdesk.com/154.html',
        'https://mm.enterdesk.com/155.html',
        'https://mm.enterdesk.com/156.html',
        'https://mm.enterdesk.com/157.html',
        'https://mm.enterdesk.com/158.html',
        'https://mm.enterdesk.com/159.html',

        'https://mm.enterdesk.com/160.html',
        'https://mm.enterdesk.com/161.html',
        'https://mm.enterdesk.com/162.html',
        'https://mm.enterdesk.com/163.html',
        'https://mm.enterdesk.com/164.html',
        'https://mm.enterdesk.com/165.html',
        'https://mm.enterdesk.com/166.html',
        'https://mm.enterdesk.com/167.html',
        'https://mm.enterdesk.com/168.html',
        'https://mm.enterdesk.com/169.html',

        'https://mm.enterdesk.com/170.html',


    ]

    def parse(self, response):
        print(111)
        imglist = response.xpath("//div/div[@class='egeli_pic_li']")
        for item in imglist:
            print(item)
            # 创建一个变量 item文件导进来
            img_itme = PythondemoItem()
            img_itme['imgsrc'] = item.xpath(".//dd//img/@src").extract_first()
            #    把数据yield到管道中去
            yield img_itme
